#!/bin/sh

#####  Increase the size of the ramdisk if needed to avoid a memory issue  ####
# https://williamlam.com/2024/03/quick-tip-using-esxcli-to-upgrade-esxi-8-x-throws-memoryerror-or-got-no-data-from-process.html
if [ $(grep mem /usr/lib/vmware/esxcli-software | cut -d = -f 3) -lt 500 ] ; then
esxcli system settings advanced set -o /VisorFS/VisorFSPristineTardisk -i 0
cp /usr/lib/vmware/esxcli-software /usr/lib/vmware/esxcli-software.bak
sed -i 's/mem=300/mem=500/g' /usr/lib/vmware/esxcli-software.bak
mv /usr/lib/vmware/esxcli-software.bak /usr/lib/vmware/esxcli-software -f
esxcli system settings advanced set -o /VisorFS/VisorFSPristineTardisk -i 1
fi

#########################  Gather Information Needed  #########################
# Get the major version that is currently running
VMWARE_VERSION=$(vmware -l | awk '{print $3}')

# Get the profile type that is currently running to make sure we update to the same
PROFILE_TYPE=$(esxcli software profile get | head -1 | cut -d - -f 4)

# Get the latest profile version
LATEST_PROFILE=$(esxcli software sources profile list -d https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml | grep ${PROFILE_TYPE} | grep ESXi-${VMWARE_VERSION} | awk '{print $5,$1}' | sort | tail -1 | awk '{print $2}')

########################  Confirm update and proceed  ########################
read -n1 -p "You are currently running profile version $(vmware -v | cut -d - -f 2).  Would you like to update to $(echo $LATEST_PROFILE | cut -d - -f 3)? (Y/N): " PROCEED

if [ "${PROCEED}" = "Y" ] || [ "${PROCEED}" = "y" ] ; then

# Ask if we can put the system into Maintenance Mode if necessary
if [ $(esxcli system maintenanceMode get) = "Disabled" ] ; then
read -n1 -p "In order to proceed, the system must be in Maintenance Mode.  Should I enable Maintenance Mode? (Y/N): " ENABLE_MAINTENANCE
     if [ "${ENABLE_MAINTENANCE}" = "Y" ] || [ "${ENABLE_MAINTENANCE}" = "y" ] ; then
          esxcli system maintenanceMode set --enable yes
     else
          echo ""
          echo "Exiting the update as we need to be in Maintenance Mode"
          exit
     fi
fi

# Allow http through the firewall so we can perform the update
esxcli network firewall ruleset set -e true -r httpClient

###############################  Do the update  ###############################
esxcli software profile update -p $LATEST_PROFILE -d https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml --no-hardware-warning

###########################  End of Proceed if Yes  ###########################

# Exit if No:
else
     echo ""
     echo "Ok, exiting...."
     exit
fi
